title: "My Blog"
description: "Imported Medium articles"
baseurl: "" # leave empty unless deploying to a subpath
url: "https://gvoden.github.io"

theme: null  # disable default theme

plugins:
  - jekyll-feed
  - jekyll-remote-theme

remote_theme: pages-themes/hacker